### PR TITLE
changed Travis to use the script deploy and removed some unused portraits

### PR DESCRIPTION
**Pull request by tparvu**
I have made some more changes and resubmitted this PR.

The big change is to the `travis.yml` to use a custom script deploy that included the `aws s3 sync --delete` option to remove unused files during deploy.

I also removed a few unused portrait images.

### CODE REVIEW

**Comment by gabmontes** [comment]
@tparvu this PR is titled "remove Phil" but is actually just removing Lexy's picture. Please elaborate.

**Comment by tparvu** [comment]
hey @gabmontes this is "removing per Phil G..."  

I spoke with Phil yesterday and he said to go ahead and remove Lexy from the site. Per my comment on the previous PR review.

If you want you can remove this PR and redo yours with Lexy's jpg removed?

**Comment by gabmontes** [comment]
@tparvu I misread the title.

**Comment by tparvu** [comment]
> @tparvu we might also want to completely remove the `releases` deploy section too.

@gabmontes I left in the releases build and packaging for now. But it probably won't be needed anymore, at least on my end.

**Pull request merged**
