### PR TITLE
Highcharts Implementation 

### PR DESCRIPTION
**Pull request by solllve**
Replaced chart with highcharts library

### CODE REVIEW

**Comment by gabmontes** [comment]
@solllve what is the goal of the change? This is what is shown with the new charts and current data:

image

Comments:
- Labels on top are redundant with labels (empty) at the bottom.
- Chart is area/lines instead of bars.
- Purple area is showing price data but should be showing tokens sold data.
- Gray/white line is flat at 0.
- X-axis labels are hours even when the time window is 7 days, so context is lost.

In addition, code linting shows this warnings that shall be solved:
[0] ./src/components/MetPriceAreaBar.js
[0]   Line 4:   'VictoryAxis' is defined but never used          no-unused-vars
[0]   Line 5:   'VictoryBar' is defined but never used           no-unused-vars
[0]   Line 6:   'VictoryChart' is defined but never used         no-unused-vars
[0]   Line 7:   'VictoryLine' is defined but never used          no-unused-vars
[0]   Line 9:   'VictoryTheme' is defined but never used         no-unused-vars
[0]   Line 21:  'smartRound' is assigned a value but never used  no-unused-vars
[0]   Line 57:  A space is required after '{'                    object-curly-spacing
[0]   Line 57:  A space is required before '}'                   object-curly-spacing
[0]   Line 64:  A space is required after '{'                    object-curly-spacing
[0]   Line 64:  A space is required before '}'                   object-curly-spacing

Finally, please branch out of `staging` and target any PR to that branch too. `staging` points to the testing site while `master` is liked to the production site.

**Comment by rcondron** [comment]
@gabmontes @solllve This change isn't for master merge, but a test that should stay in its own branch for now to see if High charts would be better for us than victory charts.

**Comment by gabmontes** [comment]
@rcondron ok, so closing this PR.

@solllve if you need to test something, you can just upload your changes to a branch but no PR is needed.

**Comment by solllve** [comment]
Hey guys, I don't have the permissions to create a branch on Autonomous... Can you please create a 'highcharts' branch, and then I'll be able to push this code there. Thanks!

**Comment by rcondron** [comment]
@solllve High-Charts branch is created.

**Comment by solllve** [comment]
@rcondron @gabmontes Scratch that. you can just pull in this request https://github.com/autonomoussoftware/metronome.io/pull/114 Thanks!

**Pull request closed without merging**
