### PR TITLE
V3 grove edits

### PR DESCRIPTION
**Pull request by thegroveco**
Last minute content updates.  Messari social additions and block on homepage.

### CODE REVIEW

**Comment by gabmontes** [comment]
@thegroveco this PR is blocked because Travis CI was not able to check the build will work after we merge the changes. We require checks both before and after the changes to enable the merge.

Can you please enable [Travis CI](https://travis-ci.com) on your repository so the PR is unblocked?

**Comment by thegroveco** [comment]
I provided access for Travis CI to check the repo on my end and triggered a build, which passed.  Let me know if there are more steps involved or anything else I need to do.

**Comment by gabmontes** [comment]
@thegroveco great!

It looks like your Travis CI run on the first commit (5edb6e1) but not on the last one (85b8085) which is the one we require to be checked before merge.

Can you please check that?

**Comment by thegroveco** [comment]
Hmmm, been poking around for bit and don't see how to do that.  I'm happy to provide you guys access to our GH account or whatever you would need to get that done.  I'm just stabbing in the dark here...

**Pull request merged**
